export const PERIODIC_TABLE_DATA = [
    { n: 1, s: 'H', name: 'Hydrogen', m: 1.008, g: 1, p: 1, c: 'Nonmetal', summary: 'The lightest element.' },
    { n: 2, s: 'He', name: 'Helium', m: 4.0026, g: 18, p: 1, c: 'Noble Gas', summary: 'Second lightest and second most abundant.' },
    { n: 3, s: 'Li', name: 'Lithium', m: 6.94, g: 1, p: 2, c: 'Alkali Metal', summary: 'Lightest metal.' },
    { n: 4, s: 'Be', name: 'Beryllium', m: 9.0122, g: 2, p: 2, c: 'Alkaline Earth', summary: 'Rare metal.' },
    { n: 5, s: 'B', name: 'Boron', m: 10.81, g: 13, p: 2, c: 'Metalloid', summary: 'Produced by cosmic ray spallation.' },
    { n: 6, s: 'C', name: 'Carbon', m: 12.011, g: 14, p: 2, c: 'Nonmetal', summary: 'Basis of all known life.' },
    { n: 7, s: 'N', name: 'Nitrogen', m: 14.007, g: 15, p: 2, c: 'Nonmetal', summary: '78% of Earth atmosphere.' },
    { n: 8, s: 'O', name: 'Oxygen', m: 15.999, g: 16, p: 2, c: 'Nonmetal', summary: 'Essential for respiration.' },
    { n: 9, s: 'F', name: 'Fluorine', m: 18.998, g: 17, p: 2, c: 'Halogen', summary: 'Most electronegative element.' },
    { n: 10, s: 'Ne', name: 'Neon', m: 20.180, g: 18, p: 2, c: 'Noble Gas', summary: 'Glows reddish-orange.' },
    { n: 11, s: 'Na', name: 'Sodium', m: 22.990, g: 1, p: 3, c: 'Alkali Metal', summary: 'Major component of salt.' },
    { n: 12, s: 'Mg', name: 'Magnesium', m: 24.305, g: 2, p: 3, c: 'Alkaline Earth', summary: 'Essential for life.' },
    { n: 13, s: 'Al', name: 'Aluminium', m: 26.982, g: 13, p: 3, c: 'Post-transition', summary: 'Most abundant metal in crust.' },
    { n: 14, s: 'Si', name: 'Silicon', m: 28.085, g: 14, p: 3, c: 'Metalloid', summary: 'Basis of semiconductors.' },
    { n: 15, s: 'P', name: 'Phosphorus', m: 30.974, g: 15, p: 3, c: 'Nonmetal', summary: 'Essential for DNA.' },
    { n: 16, s: 'S', name: 'Sulfur', m: 32.06, g: 16, p: 3, c: 'Nonmetal', summary: 'Found in amino acids.' },
    { n: 17, s: 'Cl', name: 'Chlorine', m: 35.45, g: 17, p: 3, c: 'Halogen', summary: 'Used in water purification.' },
    { n: 18, s: 'Ar', name: 'Argon', m: 39.948, g: 18, p: 3, c: 'Noble Gas', summary: '0.9% of atmosphere.' },
    { n: 19, s: 'K', name: 'Potassium', m: 39.098, g: 1, p: 4, c: 'Alkali Metal', summary: 'Important for hygiene.' },
    { n: 20, s: 'Ca', name: 'Calcium', m: 40.078, g: 2, p: 4, c: 'Alkaline Earth', summary: 'Essential for bones.' },
    { n: 21, s: 'Sc', name: 'Scandium', m: 44.956, g: 3, p: 4, c: 'Transition Metal', summary: 'Used in aerospace components.' },
    { n: 22, s: 'Ti', name: 'Titanium', m: 47.867, g: 4, p: 4, c: 'Transition Metal', summary: 'Strong and lightweight.' },
    { n: 23, s: 'V', name: 'Vanadium', m: 50.942, g: 5, p: 4, c: 'Transition Metal', summary: 'Used in steel alloys.' },
    { n: 24, s: 'Cr', name: 'Chromium', m: 51.996, g: 6, p: 4, c: 'Transition Metal', summary: 'Used in stainless steel.' },
    { n: 25, s: 'Mn', name: 'Manganese', m: 54.938, g: 7, p: 4, c: 'Transition Metal', summary: 'Essential nutrient.' },
    { n: 26, s: 'Fe', name: 'Iron', m: 55.845, g: 8, p: 4, c: 'Transition Metal', summary: 'Most common element on Earth (mass).' },
    { n: 27, s: 'Co', name: 'Cobalt', m: 58.933, g: 9, p: 4, c: 'Transition Metal', summary: 'Used in batteries.' },
    { n: 28, s: 'Ni', name: 'Nickel', m: 58.693, g: 10, p: 4, c: 'Transition Metal', summary: 'Corrosion resistant.' },
    { n: 29, s: 'Cu', name: 'Copper', m: 63.546, g: 11, p: 4, c: 'Transition Metal', summary: 'Excellent conductor.' },
    { n: 30, s: 'Zn', name: 'Zinc', m: 65.38, g: 12, p: 4, c: 'Transition Metal', summary: 'Used in galvanization.' },
    { n: 31, s: 'Ga', name: 'Gallium', m: 69.723, g: 13, p: 4, c: 'Post-transition', summary: 'Melts in your hand.' },
    { n: 32, s: 'Ge', name: 'Germanium', m: 72.630, g: 14, p: 4, c: 'Metalloid', summary: 'Early semiconductor.' },
    { n: 33, s: 'As', name: 'Arsenic', m: 74.922, g: 15, p: 4, c: 'Metalloid', summary: 'Famous poison.' },
    { n: 34, s: 'Se', name: 'Selenium', m: 78.971, g: 16, p: 4, c: 'Nonmetal', summary: 'Used in solar cells.' },
    { n: 35, s: 'Br', name: 'Bromine', m: 79.904, g: 17, p: 4, c: 'Halogen', summary: 'Liquid at room temp.' },
    { n: 36, s: 'Kr', name: 'Krypton', m: 83.798, g: 18, p: 4, c: 'Noble Gas', summary: 'Used in lighting.' },
    { n: 37, s: 'Rb', name: 'Rubidium', m: 85.468, g: 1, p: 5, c: 'Alkali Metal', summary: 'Highly reactive.' },
    { n: 38, s: 'Sr', name: 'Strontium', m: 87.62, g: 2, p: 5, c: 'Alkaline Earth', summary: 'Used in fireworks (red).' },
    { n: 39, s: 'Y', name: 'Yttrium', m: 88.906, g: 3, p: 5, c: 'Transition Metal', summary: 'Used in LEDs.' },
    { n: 40, s: 'Zr', name: 'Zirconium', m: 91.224, g: 4, p: 5, c: 'Transition Metal', summary: 'Corrosion resistant.' },
    { n: 41, s: 'Nb', name: 'Niobium', m: 92.906, g: 5, p: 5, c: 'Transition Metal', summary: 'Used in superconductors.' },
    { n: 42, s: 'Mo', name: 'Molybdenum', m: 95.95, g: 6, p: 5, c: 'Transition Metal', summary: 'High melting point.' },
    { n: 43, s: 'Tc', name: 'Technetium', m: 98, g: 7, p: 5, c: 'Transition Metal', summary: 'First artificial element.' },
    { n: 44, s: 'Ru', name: 'Ruthenium', m: 101.07, g: 8, p: 5, c: 'Transition Metal', summary: 'Rare platinum group metal.' },
    { n: 45, s: 'Rh', name: 'Rhodium', m: 102.91, g: 9, p: 5, c: 'Transition Metal', summary: 'Most valuable metal.' },
    { n: 46, s: 'Pd', name: 'Palladium', m: 106.42, g: 10, p: 5, c: 'Transition Metal', summary: 'Used in catalytic converters.' },
    { n: 47, s: 'Ag', name: 'Silver', m: 107.87, g: 11, p: 5, c: 'Transition Metal', summary: 'Best electrical conductor.' },
    { n: 48, s: 'Cd', name: 'Cadmium', m: 112.41, g: 12, p: 5, c: 'Transition Metal', summary: 'Toxic metal.' },
    { n: 49, s: 'In', name: 'Indium', m: 114.82, g: 13, p: 5, c: 'Post-transition', summary: 'Used in touch screens.' },
    { n: 50, s: 'Sn', name: 'Tin', m: 118.71, g: 14, p: 5, c: 'Post-transition', summary: 'Used in bronze.' },
    { n: 51, s: 'Sb', name: 'Antimony', m: 121.76, g: 15, p: 5, c: 'Metalloid', summary: 'Used in flame retardants.' },
    { n: 52, s: 'Te', name: 'Tellurium', m: 127.60, g: 16, p: 5, c: 'Metalloid', summary: 'Used in solar panels.' },
    { n: 53, s: 'I', name: 'Iodine', m: 126.90, g: 17, p: 5, c: 'Halogen', summary: 'Essential for thyroid.' },
    { n: 54, s: 'Xe', name: 'Xenon', m: 131.29, g: 18, p: 5, c: 'Noble Gas', summary: 'Used in flash lamps.' },
    { n: 55, s: 'Cs', name: 'Cesium', m: 132.91, g: 1, p: 6, c: 'Alkali Metal', summary: 'Used in atomic clocks.' },
    { n: 56, s: 'Ba', name: 'Barium', m: 137.33, g: 2, p: 6, c: 'Alkaline Earth', summary: 'Used in drilling fluids.' },
    { n: 57, s: 'La', name: 'Lanthanum', m: 138.91, g: 3, p: 6, c: 'Lanthanide', summary: 'Hybrid car batteries.' },
    { n: 72, s: 'Hf', name: 'Hafnium', m: 178.49, g: 4, p: 6, c: 'Transition Metal', summary: 'Nuclear control rods.' },
    { n: 73, s: 'Ta', name: 'Tantalum', m: 180.95, g: 5, p: 6, c: 'Transition Metal', summary: 'Capacitors.' },
    { n: 74, s: 'W', name: 'Tungsten', m: 183.84, g: 6, p: 6, c: 'Transition Metal', summary: 'Strongest metal.' },
    { n: 75, s: 'Re', name: 'Rhenium', m: 186.21, g: 7, p: 6, c: 'Transition Metal', summary: 'Jet engines.' },
    { n: 76, s: 'Os', name: 'Osmium', m: 190.23, g: 8, p: 6, c: 'Transition Metal', summary: 'Densest element.' },
    { n: 77, s: 'Ir', name: 'Iridium', m: 192.22, g: 9, p: 6, c: 'Transition Metal', summary: 'Corrosion resistant.' },
    { n: 78, s: 'Pt', name: 'Platinum', m: 195.08, g: 10, p: 6, c: 'Transition Metal', summary: 'Catalysts and jewelry.' },
    { n: 79, s: 'Au', name: 'Gold', m: 196.97, g: 11, p: 6, c: 'Transition Metal', summary: 'Most malleable metal.' },
    { n: 80, s: 'Hg', name: 'Mercury', m: 200.59, g: 12, p: 6, c: 'Transition Metal', summary: 'Liquid metal.' },
    { n: 81, s: 'Tl', name: 'Thallium', m: 204.38, g: 13, p: 6, c: 'Post-transition', summary: 'Highly toxic.' },
    { n: 82, s: 'Pb', name: 'Lead', m: 207.2, g: 14, p: 6, c: 'Post-transition', summary: 'Radiation shielding.' },
    { n: 83, s: 'Bi', name: 'Bismuth', m: 208.98, g: 15, p: 6, c: 'Post-transition', summary: 'Pepto-Bismol.' },
    { n: 84, s: 'Po', name: 'Polonium', m: 209, g: 16, p: 6, c: 'Metalloid', summary: 'Radioactive.' },
    { n: 85, s: 'At', name: 'Astatine', m: 210, g: 17, p: 6, c: 'Halogen', summary: 'Rarest natural element.' },
    { n: 86, s: 'Rn', name: 'Radon', m: 222, g: 18, p: 6, c: 'Noble Gas', summary: 'Radioactive gas.' },
    { n: 87, s: 'Fr', name: 'Francium', m: 223, g: 1, p: 7, c: 'Alkali Metal', summary: 'Extremely rare.' },
    { n: 88, s: 'Ra', name: 'Radium', m: 226, g: 2, p: 7, c: 'Alkaline Earth', summary: 'Once used in watches.' },
    { n: 89, s: 'Ac', name: 'Actinium', m: 227, g: 3, p: 7, c: 'Actinide', summary: 'Radioactive.' },
    { n: 104, s: 'Rf', name: 'Rutherfordium', m: 267, g: 4, p: 7, c: 'Transition Metal', summary: 'Synthetic.' },
    { n: 105, s: 'Db', name: 'Dubnium', m: 268, g: 5, p: 7, c: 'Transition Metal', summary: 'Synthetic.' },
    { n: 106, s: 'Sg', name: 'Seaborgium', m: 271, g: 6, p: 7, c: 'Transition Metal', summary: 'Synthetic.' },
    { n: 107, s: 'Bh', name: 'Bohrium', m: 272, g: 7, p: 7, c: 'Transition Metal', summary: 'Synthetic.' },
    { n: 108, s: 'Hs', name: 'Hassium', m: 270, g: 8, p: 7, c: 'Transition Metal', summary: 'Synthetic.' },
    { n: 58, s: 'Ce', name: 'Cerium', m: 140.12, g: 101, p: 8, c: 'Lanthanide', summary: 'Rare earth.' },
    { n: 59, s: 'Pr', name: 'Praseodymium', m: 140.91, g: 102, p: 8, c: 'Lanthanide', summary: 'Magnets.' },
    { n: 60, s: 'Nd', name: 'Neodymium', m: 144.24, g: 103, p: 8, c: 'Lanthanide', summary: 'Powerful magnets.' },
    { n: 61, s: 'Pm', name: 'Promethium', m: 145, g: 104, p: 8, c: 'Lanthanide', summary: 'Radioactive.' },
    { n: 62, s: 'Sm', name: 'Samarium', m: 150.36, g: 105, p: 8, c: 'Lanthanide', summary: 'Magnets.' },
    { n: 63, s: 'Eu', name: 'Europium', m: 151.96, g: 106, p: 8, c: 'Lanthanide', summary: 'Phosphors.' },
    { n: 64, s: 'Gd', name: 'Gadolinium', m: 157.25, g: 107, p: 8, c: 'Lanthanide', summary: 'MRI contrast.' },
    { n: 65, s: 'Tb', name: 'Terbium', m: 158.93, g: 108, p: 8, c: 'Lanthanide', summary: 'Green phosphors.' },
    { n: 66, s: 'Dy', name: 'Dysprosium', m: 162.50, g: 109, p: 8, c: 'Lanthanide', summary: 'Magnets.' },
    { n: 67, s: 'Ho', name: 'Holmium', m: 164.93, g: 110, p: 8, c: 'Lanthanide', summary: 'Lasers.' },
    { n: 68, s: 'Er', name: 'Erbium', m: 167.26, g: 111, p: 8, c: 'Lanthanide', summary: 'Optical fibers.' },
    { n: 69, s: 'Tm', name: 'Thulium', m: 168.93, g: 112, p: 8, c: 'Lanthanide', summary: 'X-ray machines.' },
    { n: 70, s: 'Yb', name: 'Ytterbium', m: 173.05, g: 113, p: 8, c: 'Lanthanide', summary: 'Lasers.' },
    { n: 71, s: 'Lu', name: 'Lutetium', m: 174.97, g: 114, p: 8, c: 'Lanthanide', summary: 'Cancer therapy.' },
    { n: 90, s: 'Th', name: 'Thorium', m: 232.04, g: 101, p: 9, c: 'Actinide', summary: 'Nuclear fuel potential.' },
    { n: 91, s: 'Pa', name: 'Protactinium', m: 231.04, g: 102, p: 9, c: 'Actinide', summary: 'Rare.' },
    { n: 92, s: 'U', name: 'Uranium', m: 238.03, g: 103, p: 9, c: 'Actinide', summary: 'Nuclear fuel.' },
    { n: 93, s: 'Np', name: 'Neptunium', m: 237, g: 104, p: 9, c: 'Actinide', summary: 'Synthetic.' },
    { n: 94, s: 'Pu', name: 'Plutonium', m: 244, g: 105, p: 9, c: 'Actinide', summary: 'Nuclear weapons.' },
    { n: 95, s: 'Am', name: 'Americium', m: 243, g: 106, p: 9, c: 'Actinide', summary: 'Smoke detectors.' },
    { n: 96, s: 'Cm', name: 'Curium', m: 247, g: 107, p: 9, c: 'Actinide', summary: 'Mars rovers.' },
    { n: 97, s: 'Bk', name: 'Berkelium', m: 247, g: 108, p: 9, c: 'Actinide', summary: 'Synthetic.' },
    { n: 98, s: 'Cf', name: 'Californium', m: 251, g: 109, p: 9, c: 'Actinide', summary: 'Neutron source.' },
    { n: 99, s: 'Es', name: 'Einsteinium', m: 252, g: 110, p: 9, c: 'Actinide', summary: 'Synthetic.' },
    { n: 100, s: 'Fm', name: 'Fermium', m: 257, g: 111, p: 9, c: 'Actinide', summary: 'Synthetic.' },
    { n: 101, s: 'Md', name: 'Mendelevium', m: 258, g: 112, p: 9, c: 'Actinide', summary: 'Synthetic.' },
    { n: 102, s: 'No', name: 'Nobelium', m: 259, g: 113, p: 9, c: 'Actinide', summary: 'Synthetic.' },
    { n: 103, s: 'Lr', name: 'Lawrencium', m: 262, g: 114, p: 9, c: 'Actinide', summary: 'Synthetic.' }
];
